Update Titles for social and web
dbactual/thomaspaine pull request #18
Opened 2022-07-12 06:14 UTC by tompainetoday

proposal to addresses #17

2022-07-13 21:07 UTC, dbactual commented
This looks cool, thanks. I just want to test it locally to ensure the variable replaces properly, then I can merge.

2022-11-03 15:47 UTC, tompainetoday commented
any updates on this?

2022-11-03 17:09 UTC, dbactual requested changes
Sorry, this fell off my radar a bit. This is a good change, although I've added some suggestions. I think we can drop the conditional, it's only really necessary in one case: the index of the site. Every other generated page is going to have a title. So if you approve my two suggestions removing the conditionals, then this PR only needs one additional change: you just need to modify `content/index.md` and change the title to "TPNHA". Once that is added to this pull request, this change will work for the entire site uniformly.

2022-11-03 17:09 UTC, dbactual commented on templates/header.html
> +    <meta name="og:title" content="$if(title)$${title} | $endif$ TPNHA">
```suggestion
    <meta name="og:title" content="${title} | TPNHA">
```

2022-11-03 17:09 UTC, dbactual commented on templates/header.html
> +    <title>$if(title)$${title} | $endif$ The Thomas Paine National Historical Association</title>
```suggestion
    <title>${title} | The Thomas Paine National Historical Association</title>
```

2022-12-12 02:31 UTC, tompainetoday commented
let's make it happen!

2023-01-08 18:58 UTC, dbactual approved these changes

2025-12-10 21:05 UTC, dbactual commented
Closing, as the primary TPNHA site is now run by someone else with a different code base.

2025-12-10 21:05 UTC, closed without merging